name: 'Infisical Secrets'
description: 'Use Infisical in your GitHub Actions workflow'

branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  domain:
    description: 'Infisical API domain. Helpful for self-hosted deployments, if not provided, will use the official domain.'
    required: false
  token:
    description: 'Infisical API token. (Required)'
    required: true
  projectId:
    description: 'Infisical project ID. (Required)'
    required: true
  env:
    description: 'Environment slug. (Required)'
    required: true
  path:
    description: 'Secrets path inside the environment.'
    required: false
#  format:
#    description: 'Output format.'
#    required: false
#    default: 'dotenv'
  destinationFile:
    description: 'Destination file.'
    required: false
    default: '.env'
  kubernetes:
    description: 'Should the action generate a Kubernetes secret? ("kubectl" command and context must be available)'
    required: false
    default: 'false'
  kubernetesSecretName:
    description: 'Kubernetes secret name. (Required if "kubernetes" is true)'
    required: false
  kubernetesNamespace:
    description: 'Kubernetes secret namespace.'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
